// Code generated by MockGen. DO NOT EDIT.
// Source: cards.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	entities "github.com/sultaniman/confetti/platform/entities"
)

// MockCardRepo is a mock of CardRepo interface.
type MockCardRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCardRepoMockRecorder
}

// MockCardRepoMockRecorder is the mock recorder for MockCardRepo.
type MockCardRepoMockRecorder struct {
	mock *MockCardRepo
}

// NewMockCardRepo creates a new mock instance.
func NewMockCardRepo(ctrl *gomock.Controller) *MockCardRepo {
	mock := &MockCardRepo{ctrl: ctrl}
	mock.recorder = &MockCardRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCardRepo) EXPECT() *MockCardRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCardRepo) Create(card *entities.NewCard) (*entities.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", card)
	ret0, _ := ret[0].(*entities.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCardRepoMockRecorder) Create(card interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCardRepo)(nil).Create), card)
}

// Delete mocks base method.
func (m *MockCardRepo) Delete(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCardRepoMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCardRepo)(nil).Delete), id)
}

// Get mocks base method.
func (m *MockCardRepo) Get(id uuid.UUID) (*entities.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(*entities.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCardRepoMockRecorder) Get(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCardRepo)(nil).Get), id)
}
